sudo: required
language: node_js
node_js:
  - 'stable'
cache:
directories:
  - node_modules
addons:
  postgresql: '9.6'
services:
  - postgresql
before_script:
  - psql -c 'create user ebzeal with superuser createdb createrole;' -U postgres
  - psql -c 'create database schoolmanager_test;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE schoolmanager_test TO ebzeal;' -U postgres
script:
  - npm test
after_success:
  - npm run coverage
